sudo: required
language: python
python: "3.9"
services:
  - docker
before_install:
  - docker pull conanio/gcc5
  - docker run conanio/gcc5
  - docker ps -a
install:
  # Download conan
  - sudo pip --version
  - pip install --upgrade conan
  # Automatic detection of your arch, compiler, etc
  - conan user

script:
  # Install dependencies, build, test and create package
  - conan create conan/testing --build missing